### ISSUE TITLE
Custom operator LIKE (=~) contains illegal characters

### ISSUE THREAD

**Issue by 195858** [Fizcko/rsql-mongodb#10]
Allowed character in operators are 

"custom operators - the only requirement is that they have to satisfy following regular expression: /=[a-z]+=/ (FIQL operator)."
(copied from https://github.com/piotr-oles/rsql/blob/master/README.md)

Proposal - rename to `=regex=`

**Comment by Fizcko** [comment]
Hi @195858,

I've just release a new version 2.0.0
