### ISSUE TITLE
Check a field for no equals null

### ISSUE THREAD

**Issue by woigl** [Fizcko/rsql-mongodb#15]
Hi,

Is there a way to check a field for not equaling null?
In short, check whether an optional field exists or does not exist.

This is the string I am using:
`'completedAt!=null'`

This is the output I get:
`{ completedAt: { '$ne': 'null' } }`

This is the output I would require:
`{ completedAt: { '$ne': null } }`

Is there a way to achieve this, or does this require enhancing the library?

Best Regards,
Stefan

**Comment by Fizcko** [comment]
Hi @woigl,

I've just release a new version 2.0.2 on npmjs.com. This version should fix your problem.

Regards
