### ISSUE TITLE
In comparison with a list of ObjectIds

### ISSUE THREAD

**Issue by woigl** [Fizcko/rsql-mongodb#16]
Hi,

I try to solve the following issue.

I want to use the In comparison to filter on a field of type ObjectId (i.e. the _id field). Mongo requires ObjectIds at the $in instead of strings.

That query generated by rsql-mongodb does not work:
`{ _id: { '$in': [ '650a7389a7ab39ddcfbc6832' ] } }`

The following adapted query is working:
`{ _id: { '$in': [ ObjectId('650a7389a7ab39ddcfbc6832') ] } }`

How can I get this done?

**Comment by Fizcko** [comment]
Hi @woigl,

You can try to modify the object returned by the 'rsql-mongodb' package.

Here an example:
```node
const rsqlMongoDB = require('rsql-mongodb');
const mongoose = require('mongoose');

var myQuery = rsqlMongoDB('_id=in=(650a7389a7ab39ddcfbc6832)');

function castToObjectId(obj)
{
    for (var k in obj)
    {
        if (typeof obj[k] == "object" && obj[k] !== null)
            castToObjectId(obj[k]);
        else
            if (mongoose.Types.ObjectId.isValid(obj[k]))
                if (obj[k].constructor === Array)
                    obj[k] = obj[k].map(new mongoose.Types.ObjectId);
                else
                    obj[k] = new mongoose.Types.ObjectId(obj[k])
    }
}

castToObjectId(myQuery);
console.log(myQuery);
//=> { _id: { '$in': [ new ObjectId('650a7389a7ab39ddcfbc6832') ] } }

```

**Comment by Fizcko** [comment]
@woigl Let me know if this workaround works.

If yes, i will add this natively in the package.

**Comment by woigl** [comment]
@Fizcko awesome, it works.

Please add this natively to the package; then, I would not be required to call the proposed function every time.

**Comment by Fizcko** [comment]
@woigl,

I've just release a new version 2.1.0 on npmjs.com. This version should fix your problem.

Please let me know if all is working as expected.

Regards

**Comment by woigl** [comment]
@Fizcko,

Thanks, it works for my current use case with your version 2.1.2.

I highly appreciate your fast response.
