### ISSUE TITLE
Use of RSQL reserved chars inside search values

### ISSUE THREAD

**Issue by hpk2987** [Fizcko/rsql-mongodb#17]
Maybe im not using it properly but i noticed i can't use RSQL chars (**,;()**) inside a search value even if it is wrapped in quotes.

For example running this query:
`rsqlMongoDB('lastName=="janne(doe)"');  `

Fails with 
`Wrong RSQL query. No operator found.`

If i remove the parenthesis around 'doe' it works perfectly.  Not sure if this is an issue or this chars are forbidden intentionally.

**Comment by Fizcko** [comment]
Hi @hpk2987 ,

Yes this is intentionally. Basic operators, logical operators logical and parenthesized are reserved.

If you wanna search a string using specials character you have to use regex operator.

Here an example:
```node
rsqlMongoDB('lastName=regex="janne.+doe.+"');
//=> { lastName: { '$regex': 'janne.+doe.+', '$options': '' } }
```

**Comment by woigl** [comment]
@Fizcko, just out of curiosity. Is there no way to escape those reserved characters?

If I look back to my other example with the in operator, you'll see that there is no regex involved.

I propse to consider a form of escaping.

**Comment by hpk2987** [comment]
Hi, thanks for the rapid answer.

But with that regular expression i can only search "doe" surrounded by any characters, what can i do if i need to search exactly with parenthesis (Have no problem using the regex operator but i need the parenthesis as a char specified).

**Comment by Fizcko** [comment]
@hpk2987 @woigl 

It should be possible with url encoding (Need to dev this).

But it may introduce vulnerability like injections or what ever.

```node
rsqlMongoDB('lastName==janne%28doe%29');
//=> { lastName: 'janne(doe)' }
```

**Comment by woigl** [comment]
@Fizcko, after pointing out this significant limitation, I started to worry.

Considering a simple string like `lastName=="janne(doe)"` causing an issue, is quite an issue.

Why can't we just think about escaping it like `lastName=="janne\(doe\)"`?

**Comment by Fizcko** [comment]
@hpk2987 , @woigl 

I've just release a new version 2.2.0 on npmjs.com. 

The only way to escape will be to double escape the backquote.

**Comment by woigl** [comment]
@Fizcko with 2.2.0 and escaping it works. Great job!

If I my be allowed to wish somehting, then it would be to escape single and double quotes as well. Would that be possible?

**Comment by Fizcko** [comment]
@woigl 

Yes it's works already
```node
rsqlMongoDB('lastName=="janne \"doe\""')
// => { lastName: 'janne "doe"' }
rsqlMongoDB('lastName=="janne \'doe\'"')
// => { lastName: "janne 'doe'" }
```

**Comment by woigl** [comment]
@Fizcko awesome, Thanks!
