### ISSUE TITLE
Escape chracter problem for in operator

### ISSUE THREAD

**Issue by mithundas79** [Fizcko/rsql-mongodb#18]
Version:- 2.2.0

When i try to escape character with "equal" operator it is working fine:-

```
invoice.userid="XXFF11 \\(180kW\\)\"
```

But when i try using "in" it does not

```
invoice.userid=in=(\"XXFF11 \\(180kW\\)\")
```

Can you let me know what am I doing wrong

**Comment by Fizcko** [comment]
Hi @mithundas79 ,

I've just release a new version 2.2.1 on npmjs.com. This version should fix your problem.

Regards
