### ISSUE TITLE
Regex support for RSQL

### ISSUE THREAD

**Issue by swpknl** [Fizcko/rsql-mongodb#2]
Hi,
We are passing a query which is of the form firstName=/Doe/, but we do not get the desired results.
Could you please let us know the workaround/solution for the same?

Please let us know if you need any other detail.

Regards,
Swapnil

**Comment by Fizcko** [comment]
Hi  @swpknl ,

Supposing you have a mongo collection "users" with the following documents :

```json
{
	"firstname": "John",
	"lastname": "Doe"
}
{
	"firstname": "Jeanne",
	"lastname": "Doe"
}
{
	"firstname": "Jimmy",
	"lastname": "Doedoe"
}
```
To get users where the last name is strict match "Doe", you have to do that : 
```javascript
rsqlMongoDB('lastName==Doe');
```

But if you wants to works with regex i have to implement a new operator.

If this don't responds to your question, please give me an example.

**Comment by swpknl** [comment]
Yes, we want to work with regex wherein we can get document matching a particular regex.
The == works fine. Please let me know if regex is possible to implement. Even if the /pattern/ mango operator is implemented that will also work.

Regards,
Swapnil

**Comment by Fizcko** [comment]
@swpknl 

I will implement a new operator like "=~" that will generate a query 

```
{ <field>: { $regex: /pattern/ } }
```

So you will be able to do something like that :
```javascript
rsqlMongoDB('lastName=~Doe');
//=> { "lastName": { $regex: /Doe/ } }
```

Are you agree with this ?

**Comment by Fizcko** [comment]
@swpknl 

I've juste release a new version 1.2.0

**Comment by swpknl** [comment]
Tested the same and it works fine. 

Thanks,
Swapnil
