### ISSUE TITLE
Issue with AND/OR operator

### ISSUE THREAD

**Issue by zishone** [Fizcko/rsql-mongodb#6]
Hello,

This issue is encountered when grouping the conditions with parenthesis and the first condition is not grouped.

Let's say we have this query: 
```
a==1;(b==2,c==3)
```
The package will result with:
```json
{
    "$and": [
        {
            "$or": [
                {
                    "a": 1
                },
                {
                    "b": 2
                },
                {
                    "c": 3
                }
            ]
        }
    ]
}
```
When it should be:
```json
{
    "$and": [
        {
             "a": 1
        },
        {
            "$or": [
                {
                    "b": 2
                },
                {
                    "c": 3
                }
            ]
        }
    ]
}
```
---
**There is a workaround though**
To be able to produce the desired result, the conditions were rearranged by moving the ungrouped condition to the end:
```
(b==2,c==3);a==1
```
Now this will produce the following:
```json
{
    "$and": [
        {
            "$or": [
                {
                    "b": 2
                },
                {
                    "c": 3
                }
            ]
        },
        {
            "a": 1
        }
    ]
}
```

Regards,
@zishone

**Comment by Fizcko** [comment]
Hi @zishone 

I've just release a new version 1.5.0. Can you try it and close this issue if it's ok for you ?

Thanks

**Comment by zishone** [comment]
Thanks @Fizcko! It works great, you're awesome!
