### ISSUE TITLE
JavaScript heap out of memory - invalid array length Allocation failed

### ISSUE THREAD

**Issue by subash25** [Fizcko/rsql-mongodb#8]
One of my mate was trying to perform SQL injection testing in an app which uses rsql-mongodb and he was able to crash the server with input **name=='SELECT (CHaR(75)||CHaR(76)||CHaR(77))'**

Upon looking at the code I was able to track down the issue originating in line 127 of rsql-mongodb.js. 

Kindly review the [PR](https://github.com/Fizcko/rsql-mongodb/pull/9) and resolve this ASAP.

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0x1012da6a5 node::Abort() (.cold.1) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
 2: 0x1000a6309 node::Abort() [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
 3: 0x1000a646f node::OnFatalError(char const*, char const*) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
 4: 0x1001e8f17 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
 5: 0x1001e8eb3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
 6: 0x100395db5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
 7: 0x10036db36 v8::internal::Factory::NewUninitializedFixedArray(int) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
 8: 0x1004fba41 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacityAndConvertImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
 9: 0x1004fa6d7 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::Add(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
10: 0x100585953 v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
11: 0x1005d090b v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
12: 0x1006fc839 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
13: 0x1006ffeb5 v8::internal::Runtime_SetKeyedProperty(int, unsigned long*, v8::internal::Isolate*) [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
14: 0x100a718d9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
15: 0x100a31654 Builtins_ArrayPrototypePush [/Users/sthirup/.nvm/versions/node/v14.16.1/bin/node]
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Fizcko** [comment]
Hi @subash25,

Thanks for the debug. I've just release a new version 1.5.3 on npmjs.com.

Regards
